spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/page}
    username: postgres
    password: password
  liquibase:
    change-log: classpath:db/liquibase-changeLog.yaml
    enabled: true
  jpa:
    show-sql: true
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  error:
    include-message: always
